Add context to configuration and logging errors
Add context configuration or logging errors.

Here is an example of an error with context information:

```
$ HOME=/root target/debug/display_switch
Error: failed to initialize logging

Caused by:
    0: failed to create directory: "/root/.local/share/display-switch"
    1: Permission denied (os error 13)
```